# Generated by Django 3.1 on 2020-08-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('no', models.CharField(default='aj', max_length=128)),
                ('message', models.TextField(default='Anji', max_length=128)),
            ],
        ),
    ]
