# Generated by Django 3.1 on 2020-08-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0002_auto_20200830_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_id', models.ImageField(upload_to='')),
            ],
        ),
    ]
