# Generated by Django 3.1 on 2020-08-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0003_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
    ]
