# Generated by Django 3.1 on 2020-08-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0004_delete_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='Anshul', max_length=30),
        ),
    ]
