# Generated by Django 3.1 on 2020-09-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anshul', max_length=30)),
                ('username', models.CharField(max_length=120)),
                ('phone_no', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
