# Generated by Django 3.1 on 2020-09-19 04:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile2',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='userprofile2',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
